version: '3.1'

services:

  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_MULTIPLE_DATABASES=mtservice,mtservice_auto_test
      - POSTGRES_USER=mtservice
      - POSTGRES_PASSWORD=D8rsIZP5MJjHnyv
    volumes:
      - ./deployment/local-pg-init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  nginx:
    image: nginx:stable
    restart: always
    volumes:
      - ./deployment/local-nginx.conf:/etc/nginx/nginx.conf:ro
      - ./local-logs/nginx:/var/log/nginx
    ports:
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: [ nginx-debug, '-g', 'daemon off;' ] # remove this line to not see nginx spam
